language: python
python:
  - "3.6"

cache:
  directories: 
    - $HOME/download 
    - $HOME/miniconda 


before_install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed. 
  - if test -e $HOME/miniconda/bin; then 
      echo "miniconda already installed."; 
    else 
      echo "Installing miniconda."; 
      rm -rf $HOME/miniconda; 
      mkdir -p $HOME/download; 
      if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi; 
      if [ "${MYCONDAPY}" = "2.7" ]; then 
        if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh; 
        else 
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh; 
        fi; 
      else 
        if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh; 
        else 
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh; 
        fi; 
      fi; 
      bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    fi 

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f environment.yml
  - source activate flame
  - python setup.py install

before_script:
  - sudo mkdir -m 777 /home/testmodels/
script:
  # Your test script goes here 
  - source activate flame
  - py.test -vv

sudo: required